# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source :gemcutter


gem "rake-compiler", ">=0.4.1", :group => [:development, :test]
gem "hoe", "~>2.10", :group => [:development, :test]

# vim: syntax=ruby
